# -*- coding: utf-8 -*-
"""etl_script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9mnDfT68l73XJolQazavarLqc9fXmbX
"""

# etl_script.py
import pandas as pd
import boto3
import os

def assign_popularity(followers):
    if followers > 1000:
        return 'high'
    elif followers > 500:
        return 'medium'
    else:
        return 'low'

def main():
    s3 = boto3.client('s3')

    # Environment variables set in AWS Batch Job
    bucket = os.environ['S3_BUCKET']
    input_key = os.environ['S3_INPUT_KEY']
    output_key = os.environ['S3_OUTPUT_KEY']

    local_file = '/tmp/artists.csv'
    output_file = '/tmp/cleaned_artists.csv'

    # Download file from S3
    s3.download_file(bucket, input_key, local_file)
    df = pd.read_csv(local_file)

    # Clean and transform
    df = df[df['genre'].notnull()]
    df = df[~df['genre'].str.contains(r'\d', na=False)]  # remove weird genres like "8d"
    df['popularity_level'] = df['followers'].apply(assign_popularity)

    # Save to cleaned file
    df.to_csv(output_file, index=False)

    # Upload back to S3
    s3.upload_file(output_file, bucket, output_key)
    print("ETL process complete.")

if __name__ == "__main__":
    main()